---
#  - name: iptables INPUT ACCEPT
#    iptables:
#      chain: INPUT
#      policy: ACCEPT

  - name: iptables established connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT
    notify: save iptables

  - name: iptables localhost
    iptables:
      chain: INPUT
      source: localhost
      jump: ACCEPT
    notify: save iptables

  - name: iptables SSH
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 22
      jump: ACCEPT
    notify: save iptables

  - name: iptables INPUT DROP
    iptables:
      chain: INPUT
      policy: DROP
    notify: save iptables

  - name: iptables allow ping
    iptables:
      chain: INPUT
      protocol: icmp
      icmp_type: echo-request
      jump: ACCEPT
    notify: save iptables
    tags: ["dev", "icmp", "iptables"]

  - name: iptables allow ping reply
    iptables:
      chain: OUTPUT
      protocol: icmp
      icmp_type: echo-reply
      jump: ACCEPT
    notify: save iptables
    tags: ["dev", "icmp", "iptables"]

    #   - iptables:
     #chain: INPUT
     #policy: DROP
