---
  - name: Debug
    debug:
      var: inventory_hostname
  - name: Debug
    debug:
      var: ansible_hostname

  - name: Gathering OS Family facts
    setup:
      filter: 'ansible_os_family'
    #setup: filter='*'
    tags: common

  - name: include common tasks
    include: common.yml
    tags: common

  - name: include profiles config
    include: profiles.yml
    tags: common, profiles

  - name: include users config
    include: user_config.yml
    tags: common

#  - name: include iptables task
#    include: iptables.yml
#    tags: ["common", "iptables"]

  - name: include ssh task
    include: ssh.yml
    tags: common, ssh

  # Install packages
  - name: Install packages
    include: packages.yml
    tags: common, packages
