---
  - name: Gathering OS Family facts
    setup: filter='ansible_os_family'
    #setup: filter='*'
    tags: common

  - name: include profiles config
    include: profiles.yml
    tags: common

  - name: include Debian tasks
    include: debian.yml
    when: (ansible_os_family == "Debian")
    tags: common

  - name: include RedHat tasks
    include: redhat.yml
    when: (ansible_os_family == "RedHat")
    tags: common

  - name: installing common packages
    package:
      pkg: "{{ item }}"
      update_cache: yes
    with_items:
      - "{{ packages }}"
    tags: common, packages

#  - name: include iptables task
#    include: iptables.yml
#    tags: ["common", "iptables"]

  - name: include ssh task
    include: ssh.yml
    tags: common, ssh

  - name: Set timezone to Europe/Moscow
    timezone:
      name: Europe/Moscow
    tags: common

  - name: Set hostname
    hostname:
      name: "{{ hostname }}"
    when: hostname != "default"
    tags: common

