---
  # DEBIAN
  - name: installing Debian/Ubuntu packages
    package:
      pkg: "{{ item }}"
      update_cache: yes
    with_items:
      - "{{ deb_packages }}"
    when: install_packages == true and ansible_os_family == "Debian"
    tags: ["common", "packages"]


  # REDHAT
  - name: Check if EPEL repo is already configured.
    stat: path={{ epel_repofile_path }}
    register: epel_repofile_result
    when: install_packages == true and ansible_os_family == "RedHat"

  - name: Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result
    when: install_packages == true and ansible_os_family == "RedHat" and (not epel_repofile_result.stat.exists)

  - name: Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: install_packages == true and ansible_os_family == "RedHat" and (not epel_repofile_result.stat.exists)

  - name: install RHEL/CentOS packages
    package:
      pkg: "{{ item }}"
      update_cache: yes
    with_items:
      - "{{ rh_packages }}"
    when: install_packages == true  and ansible_os_family == "RedHat"
    tags: ["common", "packages"]


  # COMMON PACKAGES
  - name: installing common packages
    package:
      pkg: "{{ item }}"
      update_cache: yes
    with_items:
      - "{{ packages }}"
    when: install_packages == true
    tags: common, packages

  - name: installing additional packages
    package:
      pkg: "{{ item }}"
      update_cache: no
    with_items:
      - "{{ additional_packages | default([]) }}"
    when: install_additional_packages == true
    tags: common, packages
