---
  # Проверяем, созданы ли профили пользоветелей
  # тк используется with_items, результат будет сохранен в объект dictionary (results [])
  - name: "Save user {{ item }} profile path"
    shell: "getent passwd '{{ item }}' | cut -d: -f6"
    register: user_profile_path
    with_items:
      - "{{ config_users }}"
    ignore_errors: true
    tags: profile, copy, ssh_keys

  # - name: Check users profile path
  #   debug:
  #     msg: "name (item): {{ item.item }}, stdout: {{ item.stdout }}, stderr: {{ item.stderr }}" #" path: {{ item.user.invocation.module_args.path }}" #" exist: {{item.stat.exists}}, item_name:{{item.item}}, path: {{item.invocation.module_args.path}}"
  #   with_items:
  #     - "{{ user_profile_path.results }}"
  #   #when: item.stdout != ""
  #   tags: profile, copy, ssh_keys, debug

  # Копируем файлы в профили пользователей (если они есть)
  # config_users находится внутри user_profile_exists.results.item
  - name: Copy files to users profile
    copy:
      src: files/profile/
      dest: "{{ item.stdout }}" #{{item.invocation.module_args.path}}
      owner: "{{ item.item }}"
      group: "{{ item.item }}"
    with_items:
      - "{{ user_profile_path.results }}"
    when: item.stdout != ""
    tags: profile, copy

  - name: Copy files to skel
    copy:
      src: files/profile/
      dest: /etc/skel/
    tags: profile, copy