---
  - name: Copy files to root profile
    copy:
      src: files/profile/
      dest: /root/
      mode: preserve
    tags: profile, copy

  - name: Copy files to skel
    copy:
      src: files/profile/
      dest: /etc/skel/
    tags: profile, copy

#  - name: "Check users profile debug2 "
#    debug:
#      msg: "exist: {{item.stat.exists}}, item_name:{{item.item}}, path: {{item.invocation.module_args.path}}"
#    with_items: "{{user_profile_exists.results}}"
#    tags: profile, copy, debug

  # способ получить домашний каталог юзера
  # getent passwd "$USER" | cut -d: -f6

  # Проверяем, созданы ли профили пользоветелей
  - name: "Check users profile {{ item }} exist"
    stat:
      path: "/home/{{ item }}"
    register: user_profile_exists
    with_items:
      - "{{ config_users }}"
    ignore_errors: true
    tags: profile, copy, debug

  # Копируем файлы в профили пользователей (если они есть)
  # config_users находится внутри user_profile_exists.results.item
  - name: Copy files to users profile
    copy:
      src: files/profile/
      dest: /home/{{ item.item }}/ #{{item.invocation.module_args.path}}
      owner: "{{ item.item }}"
      group: "{{ item.item }}"
    with_items:
      - "{{user_profile_exists.results}}"
    when: item.stat.exists == True
    tags: ["profile", "copy"]