---
  - name: SSH TCPKeepAlive {{ ssh.TCPKeepAlive }}
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^TCPKeepAlive'
      line: TCPKeepAlive {{ ssh.TCPKeepAlive }}
    notify:
      - Reload sshd
    tags: ["ssh"]

  - name: SSH ClientAliveInterval {{ ssh.ClientAliveInterval }}
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^ClientAliveInterval'
      line: ClientAliveInterval {{ ssh.ClientAliveInterval }}
    notify:
      - Reload sshd
    tags: ["ssh"]

  - name: SSH ClientAliveCountMax {{ ssh.ClientAliveCountMax }}
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^ClientAliveCountMax '
      line: ClientAliveCountMax {{ ssh.ClientAliveCountMax }}
    notify:
      - Reload sshd
    tags: ["ssh"]