---
  - name: SSH TCPKeepAlive {{ ssh.TCPKeepAlive }}
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^TCPKeepAlive'
      line: TCPKeepAlive {{ ssh.TCPKeepAlive }}
    notify:
      - Reload sshd
    tags: ssh

  - name: SSH ClientAliveInterval {{ ssh.ClientAliveInterval }}
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^ClientAliveInterval'
      line: ClientAliveInterval {{ ssh.ClientAliveInterval }}
    notify:
      - Reload sshd
    tags: ssh

  - name: SSH ClientAliveCountMax {{ ssh.ClientAliveCountMax }}
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^ClientAliveCountMax '
      line: ClientAliveCountMax {{ ssh.ClientAliveCountMax }}
    notify:
      - Reload sshd
    tags: ssh

  - name: Set authorized key taken from file for ROOT
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    tags: ssh, ssh_keys

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    with_items:
      - "{{user_profile_exists.results}}"
    when: item.stat.exists == True
    tags: ssh, ssh_keys
