---
  - name: include Debian handlers
    include: debian.yml
    when: (ansible_os_family == "Debian")
    tags: ["common"]

  - name: include RedHat handlers
    include: redhat.yml
    when: (ansible_os_family == "RedHat")
    tags: ["common"]

  - name: Restart systemd-timesyncd
    service:
      name: systemd-timesyncd
      state: restarted

  - name: Reload sshd
    service:
      name: sshd
      state: reloaded

  - name: Restart sshd
    service:
      name: sshd
      state: restarted